clang-tidy: Fix override errors
The following errors were reported during the clang-tidy enablement
build due to overridden functions not being marked with the override
keyword. The proposed fix is to add the override keyword where it
was missing.

'''
1m../tools/i2c/i2c.hpp:176:10:
  error: 'open' overrides a member function but is not marked 'override' [-Werror
1m../tools/i2c/i2c.hpp:179:10:
  error: 'isOpen' overrides a member function but is not marked 'override' [-Werror
1m../tools/i2c/i2c.hpp:185:10:
   error: 'close' overrides a member function but is not marked 'override' [-Werror
'''

Tested: Verified Build and unit testing.

Change-Id: Iad01481761c6a4339e051c183c3dd238baf19d70
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>