clang-tidy: Remove unused private field
The following errors were reported during clang-tidy enablement due
to unused private field.

'''
 tools/i2c/i2c.hpp:43:13: error: private field 'busId' is not used [-Werror
'''

The fix involves removing these unused private field 'busId'.

Tested: Build and unit testing verified.

Change-Id: I1fac353707e250ff661d4f42abdb1a2e9bb3a689
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>