clang-tidy: Suppress unused private field warning
Addressed warnings reported during clang-tidy enablement by marking
unused private fields with the [[maybe_unused]] keyword in multiple
instances. This temporarily suppresses the warnings until a permanent
solution is implemented.

'''
./phosphor-regulators/src/manager.hpp:199:31: error: private field 'eventLoop' is not used [-Werror
./phosphor-regulators/src/dbus_sensor.hpp:316:23: error: private field 'bus' is not used [-Werror
'''

Tested: Verified build and unit testing.

Change-Id: I5c4424deaee8440c619f8d541ee6203c4d9d738b
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>