meson: Fix local meson build
Currently local meson build fails with the error message:
"""
In file included from ../phosphor-power-sequencer/src/services.cpp:17:
../phosphor-power-sequencer/src/services.hpp:19:10: fatal error:
xyz/openbmc_project/Logging/Entry/server.hpp: No such file or directory
   19 | #include "xyz/openbmc_project/Logging/Entry/server.hpp"
"""
Provide missing meson dependency to fix the issue.

Tested:
"meson setup build && cd build && meson compile" finishes successfully.

Change-Id: I0c13a6bfc8014d201b2cf6364c87059726d0c464
Signed-off-by: Konstantin Aladyshev <aladyshev22@gmail.com>