Update chassis-status-tool: Add property filtering and improve usability
Adds an option to specify what properties to include in display.
Adds an option to specify a number to include all chassis up to
and including that number in the display. Adds method to determine the
number of chassis on the system. Rename 'dump' subcommand
to 'display' and make it optional. Makes tool default to display
subcommand when none specified. Changes verbose output to include
error messages, error messages no longer included in normal output.

Tested:
- Verified number of chassis with huygens.json config.
- Verified new property option works with all properties
- Verified new -n option works and conflicts with option
  to specify any one chassis number.
- Verified property option rejects invalid properties
- Verified default subcommand works as intended.

'''
root@huygens:/tmp# chassis-status-tool -c 1 -p Enabled

Chassis 1
    Enabled: True

root@huygens:/tmp# chassis-status-tool display -c 1 -p Enabled

Chassis 1
    Enabled: True

root@huygens:/tmp# chassis-status-tool display -c 1 -p Enabled Present

Chassis 1
    Present: True
    Enabled: True

root@huygens:/tmp# chassis-status-tool display -c 1 -p wrong
Error: Unknown property 'wrong'

root@huygens:/tmp# chassis-status-tool wrong
The following argument was not expected: wrong
Run with --help for more information.

root@huygens:/tmp# chassis-status-tool -n 2 -p Enabled

Chassis 0
    Enabled: True

Chassis 1
    Enabled: True

Chassis 2
    Enabled: True

root@huygens:/tmp# chassis-status-tool -n 2 -c 1
-c excludes -n
Run with --help for more information.

root@huygens:/tmp# chassis-status-tool -c 1 -p PowerSupplyStatus

Chassis 1
    Power Supply Status: Unknown

root@huygens:/tmp# chassis-status-tool -c 1 -p PowerSupplyStatus -v

Chassis 1
    Power Supply Status: Unknown
       Power supplies power Status property value could not be obtained.
       Object Path: /xyz/openbmc_project/power/power_supplies/chassis1/psus
       Interface: xyz.openbmc_project.State.Decorator.PowerSystemInputs

root@huygens:/tmp# chassis-status-tool -h
Chassis status tool
Usage: chassis-status-tool [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
  -c INT Excludes: -n         Specify a number from 1 to n, where n is the number of the chassis
  -n INT Excludes: -c         Specify a number n, include all the chassis up to and including n
  -p TEXT                     Specify what properties to display
  -v,--verbose                Include D-Bus object paths, interface names, and error details in output

Subcommands:
  display                     Display chassis status (default if no subcommand given)

Properties:
  * Present
  * Available
  * Enabled
  * PowerState
  * PowerGood
  * InputPowerStatus
  * PowerSupplyStatus
'''

Change-Id: I89ce2400135b8a0e937e7b263d63422a692e209e
Signed-off-by: Brendan Singer <brendansinger2@gmail.com>