clang-tidy: Suppress move assignment warning
The following error was reported during clang-tidy enablement due to
the explicitly defaulted move assignment operator being implicitly
deleted. This temporary fix suppresses the warning using Meson build
configuration until a permanent solution is implemented.

'''
phosphor-regulators/src/config_file_parser_error.hpp:39:28:
     error: explicitly defaulted move assignment operator is implicitly deleted [-Werro
phosphor-regulators/src/pmbus_error.hpp:38:17:
    error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
phosphor-regulators/src/write_verification_error.hpp:41:29:
    error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
pmbus.hpp:216:12: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
gpio.hpp:53:11: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
pmbus.hpp:214:12: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror
device.hpp:25:13: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
phosphor-power-sequencer/src/config_file_parser_error.hpp:37:28:
    error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror
power-sequencer/mihawk-cpld.hpp:32:17:
    error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
power-sequencer/ucd90160.hpp:38:15:
    error: explicitly defaulted move assignment operator is implicitly deleted [-Werror
'''

Tested: Verified build and unit testing.

Change-Id: I123e7ba0fdcd7d3e8f74c8e333a3294046a152d7
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>