clang-tidy: Suppress unused lambda capture warn
The following errors were reported during clang-tidy enablement due to
unused lambda captures. This temporary fix suppresses the warnings using
pragma diagnostic ignore checks until a permanent solution is implemented.

Changes:
- Added pragma directives to suppress the -Wunused-lambda-capture warning
  in specific code sections.

'''
cold-redundancy/cold_redundancy.cpp:50:23: error: lambda capture 'objectServer' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:59:44: error: lambda capture 'io' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:59:49: error: lambda capture 'objectServer' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:50:18: error: lambda capture 'io' is not used [-Werror
'''

Tested: Build and unit testing verified.

Change-Id: If18b25f6ab09f3c369899777ba313400604a24ec
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>