clang-tidy: Remove unused lambda captures
The following errors were reported during clang-tidy enablement due
to unused lambda captures.

'''
cold-redundancy/cold_redundancy.cpp:50:23: error: lambda capture 'objectServer' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:59:44: error: lambda capture 'io' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:59:49: error: lambda capture 'objectServer' is not used [-Werror
cold-redundancy/cold_redundancy.cpp:50:18: error: lambda capture 'io' is not used [-Werror
'''

The fix involves removing these unused lambda captures.

Tested: Build and unit testing verified.

Change-Id: If18b25f6ab09f3c369899777ba313400604a24ec
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>